### ISSUE TITLE
help me with this error

### ISSUE THREAD

**Issue by sakshi307** [AdityaPai2398/Get_Live_Cricket_Score#1]
Traceback (most recent call last):
  File "cricscore.py", line 55, in <module>
    send_message=match_obj.get_unique_id()
  File "cricscore.py", line 22, in get_unique_id
    for i in resp_dict['matches']:
KeyError: 'matches'

**Comment by AdityaPai2398** [comment]
Change the tam name to the one that is currently live and it should work
